// remove ingredients that do not return any cocktails

export const blacklist = [
  '7-up',
  'Aejo Rum',
  'Aftershock',
  'Allspice Dram',
  'Arrack',
  'Averna',
  'Bacardi',
  'Banana Rum',
  'Banana Syrup',
  'Barenjager',
  'Beef Stock',
  'Black Pepper',
  'Black Rum',
  'Blackberry Schnapps',
  'Blackcurrant Schnapps',
  'Blue Maui',
  'Calvados',
  'Canadian Whisky',
  'Candy',
  'Carbonated Soft Drink',
  'Celery',
  'Celery Salt',
  'Chareau',
  'Cherry Cola',
  'Cinnamon Whisky',
  'Clamato Juice',
  'Cocchi Americano',
  'Cocktail Onion',
  'Coconut Cream',
  'Cola',
  'Cold Water',
  'Coochi Americano',
  'Cream Sherry',
  'Cream Soda',
  'Creme De Noyaux',
  'Creme De Almond',
  'Creme de Violette',
  'Cumin Powder',
  'Cumin Seed',
  'Cynar',
  'Dark Soy Sauce',
  'Dried Oregano',
  'Dry Curacao',
  'Eggnog',
  'Fanta',
  'Fernet-Branca',
  'Forbidden Fruit',
  'Fresca',
  'Garlic Sauce',
  'Glycerine',
  'Grapes',
  'Ground Ginger',
  'Habanero Peppers',
  'Hawaiian punch',
  'Hazelnut liqueur',
  'Hooch',
  'Ice-Cream',
  'Ilegal Joven mezcal',
  'Jelly',
  'Key Largo Schnapps',
  'Lemon soda',
  'lemon-lime',
  'Lime linqueur',
  'Madeira',
  'Mandarin',
  'Mandarin napoleon',
  'Margarita mix',
  'Marjoram leaves',
  'Martini Bianco',
  'Martini Extra Dry',
  'Melon Vodka',
  'Mini-snickers bars',
  'Nocino',
  'Olive Oil',
  'Onion',
  'Orange rum',
  'Oyster Sauce',
  'Parfait amour',
  'Peanut Oil',
  'Pineapple-orange-banana juice',
  'Pineapple rum',
  'Plain Chocolate',
  'Plain Flour',
  'Plums',
  'Purple passion',
  'Raisins',
  'Ramazzotti',
  'Raspberry Jam',
  'Red Bull',
  'Red Chile Flakes',
  'Red Hot Chili Flakes',
  'Rhubarb',
  'Rock Salt',
  'Root beer schnapps',
  'Salt',
  'Singani',
  'Sour Apple Pucker',
  'Soy Milk',
  'Soya Milk',
  'Sprite',
  'Squeezed Orange',
  'Strawberry juice',
  'Sunny delight',
  'Tajin',
  'Tang',
  'Tequila rose',
  'Tomato',
  'Tuaca',
  'Water',
  'White chocolate liqueur',
  'White grape juice',
  'White port',
  'White Vinegar',
]