// remove ingredients that do not return any cocktails

export const blacklist = [
  'Aejo Rum',
  'Aftershock',
  'Allspice Dram',
  'Arrack',
  'Averna',
  'Bacardi',
  'Banana Rum',
  'Banana Syrup',
  'Barenjager',
  'Beef Stock',
  'Black Pepper',
  'Black Rum',
  'Blackberry Schnapps',
  'Blackcurrant Schnapps',
  'Blue Maui',
  'Calvados',
  'Canadian Whisky',
  'Candy',
  'Carbonated Soft Drink',
  'Celery',
  'Chareau',
  'Cinnamon Whisky',
  'Clamato Juice',
  'Cocktail Onion',
  'Coconut Cream',
  'Cola',
  'Cold Water',
  'Coochi Americano',
  'Cream Sherry',
  'Cream Soda',
  'Creme De Noyaux',
  'Creme De Almond',
  'Cumin Powder',
  'Cynar',
  'Dark Soy Sauce',
  'Dried Oregano',
  'Fanta',
  'Forbidden Fruit',
  'Fresca',
  'Garlic Sauce',
  'Glycerine',
  'Ground Ginger',
  'Habanero Peppers',
  'Hawaiian punch',
  'Hazelnut liqueur',
  'Hooch',
  'Ice-Cream',
  'Ilegal Joven mezcal',
  'Jelly',
  'Key Largo Schnapps',
  'lemon-lime',
  'Lime linqueur',
  'Madeira',
  'Mandarin',
  'Mandarin napoleon',
  'Margarita mix',
  'Marjoram leaves',
  'Martini Extra Dry',
  'Melon Vodka',
  'Mini-snickers bars',
  'Nocino',
  'Olive Oil',
  'Onion',
  'Orange rum',
  'Oyster Sauce',
  'Parfait amour',
  'Peanut Oil',
  'Pineapple-orange-banana juice',
  'Pineapple rum',
  'Plain Chocolate',
  'Plain Flour',
  'Plums',
  'Purple passion',
  'Red Bull',
  'Red Chile Flakes',
  'Red Hot Chili Flakes',
  'Rhubarb',
  'Rock Salt',
  'Root beer schnapps',
  'Singani',
  'Soy Milk',
  'Soya Milk',
  'Strawberry juice',
  'Sunny delight',
  'Tajin',
  'Tang',
  'Tequila rose',
  'Tomato',
  'Tuaca',
]